### ISSUE TITLE
🐛 Fix build bustage of Grizzly

### ISSUE THREAD

**Issue by posidron** [MozillaSecurity/orion#31]
https://api.travis-ci.org/v3/job/488277277/log.txt

```
[Monorepo] DockerHub (build) INFO: Building image for services/grizzly/Dockerfile
Sending build context to Docker daemon  2.232kB


Step 1/8 : FROM mozillasecurity/fuzzos:latest
latest: Pulling from mozillasecurity/fuzzos
Digest: sha256:69c7bad5faadc6d1974fcedb83c8cbe77f09aa8879fb8f7d49b52ca39bf49019
Status: Image is up to date for mozillasecurity/fuzzos:latest
 ---> c54facd88970
Step 2/8 : LABEL maintainer Jesse Schwartzentruber <truber_mozilla.com>
 ---> Running in 8ae6fc7b7700
Removing intermediate container 8ae6fc7b7700
 ---> 2a1cd2c3a60d
Step 3/8 : USER root
 ---> Running in 862029d51d69
Removing intermediate container 862029d51d69
 ---> f29af429870c
Step 4/8 : COPY recipes/ /tmp/recipes/
 ---> cfe6068535bb
Step 5/8 : RUN /tmp/recipes/grizzly.sh     && rm -rf /tmp/recipes
 ---> Running in 2eb404ce044b
[91m+ apt-get update -y -qq
[0m[91m+ cat
[0m[91m++ lsb_release -cs
[0m[91m++ lsb_release -cs
[0m[91m++ lsb_release -cs
[0m[91m+ curl -sL http://ddebs.ubuntu.com/dbgsym-release-key.asc
[0m[91m+ apt-key add -
[0m[91mWarning: apt-key output should not be parsed (stdout is not a terminal)
[0mOK
[91m+ apt-get update -y -qq
[0m[91m+ apt-get install -q -y libasound2 libdbus-glib-1-2 libglu1-mesa libglu1-mesa-dbgsym libosmesa6 libpulse0 libwayland-egl1-mesa-dbgsym nodejs p7zip-full python-dev python-setuptools python-wheel screen subversion ubuntu-restricted-addons virtualenv wget xvfb zip
[0mReading package lists...
Building dependency tree...
Reading state information...
python-setuptools is already the newest version (39.0.1-2).
xvfb is already the newest version (2:1.19.6-1ubuntu4.2).
nodejs is already the newest version (10.15.1-1nodesource1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libwayland-egl1-mesa-dbgsym : Depends: libwayland-egl1-mesa (= 18.0.0~rc5-1ubuntu1)
[91mE: Unable to correct problems, you have held broken packages.
[0mThe command '/bin/sh -c /tmp/recipes/grizzly.sh     && rm -rf /tmp/recipes' returned a non-zero code: 100
Traceback (most recent call last):
  File "./monorepo.py", line 409, in <module>
    sys.exit(MonorepoManager.main())
  File "./monorepo.py", line 393, in main
    Travis().run(args)
  File "./monorepo.py", line 253, in run
    self.deliver(folder, options, version)
  File "./monorepo.py", line 236, in deliver
    docker.build()
  File "./monorepo.py", line 127, in build
    os.path.dirname(self.dockerfile)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '--compress', '-t', 'mozillasecurity/grizzly:nightly', '-t', 'mozillasecurity/grizzly:latest', '-f', 'services/grizzly/Dockerfile', 'services/grizzly']' returned non-zero exit status 100
```

Also the following packages can be removed as they are in present in the base image:

```
xvfb, nano, nodejs, python-setuptools
```

The base image comes with `unzip` and `bzip2` whereby this image installs `p7zip-full` and `zip`. We should analyze the use cases and remove either or.

**Comment by jschwartzentruber** [comment]
Fixed the bustage in bbcbbc7321b35c5bbe8dc1729549cefc56580829. I'll look at eliminating duplicates soon.
